name: openclassrooms

services:
  puls_events_rag:
    build: .
    container_name: puls_events_rag_api
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    name: openclassrooms
